from collections.abc import Mapping
from typing import Any

from . import events as events

__version__: str
GENESIS_PARENT_HASH: str

class SigningKeypair:
    @staticmethod
    def generate() -> SigningKeypair: ...
    @staticmethod
    def load(path: str) -> SigningKeypair: ...
    @staticmethod
    def load_or_create(path: str) -> SigningKeypair: ...
    def save(self, path: str) -> None: ...
    @property
    def pubkey_hex(self) -> str: ...

class SignedEvent:
    @property
    def seq(self) -> int: ...
    @property
    def timestamp_nanos(self) -> int: ...
    @property
    def event(self) -> dict[str, Any]: ...
    @property
    def parent_hash(self) -> str: ...
    @property
    def self_hash(self) -> str: ...
    @property
    def signature(self) -> str: ...
    @property
    def signer_pubkey(self) -> str: ...
    def to_json(self) -> str: ...

class Session:
    @staticmethod
    def open(
        *, keypair: SigningKeypair, ledger_path: str, session_id: str
    ) -> Session: ...
    def record(self, event: events.AgentEvent) -> SignedEvent: ...
    @property
    def session_id(self) -> str: ...
    @property
    def pubkey_hex(self) -> str: ...

class ChainReport:
    @property
    def ok(self) -> bool: ...
    @property
    def status(self) -> str: ...
    @property
    def event_count(self) -> int: ...
    @property
    def broken_at(self) -> int | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def root_hash(self) -> str: ...

def sign_event(
    *, event: events.AgentEvent, seq: int, parent_hash: str, keypair: SigningKeypair
) -> SignedEvent: ...
def compute_self_hash(
    *, seq: int, timestamp_nanos: int, event: events.AgentEvent, parent_hash: str
) -> str: ...
def verify_chain(events: list[SignedEvent]) -> ChainReport: ...
def verify_file(path: str) -> ChainReport: ...
def canonical_json(
    value: Mapping[str, Any] | list[Any] | str | int | float | bool | None,
) -> bytes: ...

class ProvedexError(Exception): ...
class KeyLoadError(ProvedexError): ...
class SigningError(ProvedexError): ...
class LedgerError(ProvedexError): ...
class ChainError(ProvedexError): ...
