from collections.abc import Mapping
from typing import Any

class AgentEvent: ...

def session_started(*, agent_id: str, model_id: str, session_id: str) -> AgentEvent: ...
def utterance_captured(
    *, audio_sha256: str, transcript: str, lang: str, duration_ms: int
) -> AgentEvent: ...
def tool_called(
    *, tool_name: str, args_sha256: str, args_redacted: Mapping[str, Any] | list[Any]
) -> AgentEvent: ...
def tool_returned(
    *, tool_name: str, result_sha256: str, latency_ms: int, success: bool
) -> AgentEvent: ...
def model_invoked(
    *, model_id: str, prompt_sha256: str, response_sha256: str,
    prompt_tokens: int, response_tokens: int,
) -> AgentEvent: ...
def utterance_spoken(*, text_sha256: str, text: str, audio_sha256: str) -> AgentEvent: ...
def session_ended(*, reason: str, summary_sha256: str) -> AgentEvent: ...
def from_dict(value: Mapping[str, Any]) -> AgentEvent: ...
